### ISSUE TITLE
Settle on a theme

### ISSUE THREAD

**Issue by moffutt10** [nss-evening-cohort-8/bandz-van-gogh-s-ear#11]
## User Story
As a user I should be greeted by some sweet colors, and a nice comforting theme.

## Development
- Pick something from word press that looks cool
- Theme should evoke jaaaaaaazz :trumpet: :saxophone:

## Acceptance Criteria
Majority rules.

**Comment by Waysidetester** [comment]
👍

**Comment by charleswoodring** [comment]
👍
