### ISSUE TITLE
JS object for tour info to print to DOM

### ISSUE THREAD

**Issue by colinlwhite** [nss-evening-cohort-8/bandz-van-gogh-s-ear#17]

**Comment by colinlwhite** [comment]
# Story 
* As a user, in order to see when the band is performing, I need to be able to view the information on the tour page. 

# Acceptance Criteria 
**When** the user clicks on the "Tour" link in the navigation bar
**Then** the user should see the uploaded page
**And** be able to view the tour dates for the next few months
**And** be able to purchase tickets for the tour
**And** be able to click to the venue and see information about that

# Technical Notes
* Create a tourInfo object
* Create a tourString function
* Loop through the tourInfo object 
* Print the function to the DOM

**Comment by charleswoodring** [comment]
👍
