### ISSUE TITLE
JS for home page. Loop through paragraphs.

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/bandz-van-gogh-s-ear#18]
## User story
* As a user, I should be able to see the Band name as a heading
* As a user, I should be able to see the Band's backstory
* As a user, I should be able to see an image of the band

## Dev notes
* Store band's backstory as an array
* Loop through the array to print each array item to the DOM
* Upon loop's completion, print the image to the DOM
* Put class/id on items for styling purposes

## Acceptance
* We should see the band name as a title
* We should see some biography information about the band
* We should see a band photo

**Comment by colinlwhite** [comment]
![image from ios](https://user-images.githubusercontent.com/36483871/45393337-15114800-b5f1-11e8-90e0-28c1bada0d74.jpg)
