### ISSUE TITLE
Create Band Members

### ISSUE THREAD

**Issue by charleswoodring** [nss-evening-cohort-8/bandz-van-gogh-s-ear#2]
## User story
As a user, I should be able to see an HTML page that contains band member bios.

## Dev notes
* Create  HTML
* Link to CSS file
* Link to JS file

## Acceptance
* We should be able to see the background color change 
* The console should be logging "I am linked"
* The page should be viewable by the browser

**Comment by moffutt10** [comment]
This looks good!!! 🌮
