### ISSUE TITLE
Create Tour Dates

### ISSUE THREAD

**Issue by colinlwhite** [nss-evening-cohort-8/bandz-van-gogh-s-ear#3]

**Comment by colinlwhite** [comment]
# Story 
* As a user, in order to know when the band is performing, I need to be able to view the Tour Page. 

# Acceptance Criteria 
**When** the user clicks on the "Tour" link in the navigation bar
**Then** the user should see the uploaded page
**And** be able to view the tour dates for the next few months
**And** be able to purchase tickets for the tour

# Technical Notes
* Create tour.html file
* Create <div> element
* Create an ID within the <div> element

**Comment by charleswoodring** [comment]
Looks good.  Let's get on the road 👍
