### ISSUE TITLE
Create Homepage (index.html)

### ISSUE THREAD

**Issue by Waysidetester** [nss-evening-cohort-8/bandz-van-gogh-s-ear#7]
## User story
As a user, I should be able to see an HTML page. It may or may not have any content in it.

## Dev notes
* Create skeleton :skull: HTML
* Link to CSS file
* Link to JS file
* Link to background image
* H1 title div for "Van Gogh's Ear"
* H2 div for "Nashville Jazz Collective"
* H2 div for About Us
* P div for band bio
* nav
* footer 👣 

## Acceptance
* The console should be logging "I am linked"
* The page should be viewable by the browser

![homepage](https://user-images.githubusercontent.com/40044635/45376667-08273100-b5be-11e8-9ab2-552fe78a45bb.png)

**Comment by Waysidetester** [comment]
👍

**Comment by charleswoodring** [comment]
👍
